### ISSUE TITLE
Update properties in glove

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-react-ui#176]

**Comment by davidradl** [comment]
I am developing the update capability.

Currently in glove (the visualisation in glossary author based on the idea of rex):
- there is the concept of a traversal, this is a new search that contains arrays of nodes and relationships   
- every subsequent traversal creates a gen. 
- if a traversal is a created that does not contain any new nodes ore relationships then we do not create a new gen.  

therefore the gens are immutable and a node only exists in one gen.

If I do an update node, I cannot use the existing methods as the node will already  exist. 
 so
1)  updating the node in generation that is was introduced, in this case I loose the state that the node was.
2) the existing code shows outdates nodes, if a node changed underneath us after we have put it in a gen

At the moment, I see the simplest thing to do is to:
-  update in place, there is no history or ability to undo,  
- a traversal still means new nodes on the canvas

The approach could also be used for delete, but for delete node - I think I might need to find all the relationships that refer to the node and delete them, unless they are ignores. 

any thoughts @mandy-chessell @cmgrote @planetf1 @sarbull

**Comment by planetf1** [comment]
For server author, I would expect that in a k8s operator environment it's likely we want to prevent any control of servers (start, stop etc) as this conflicts with operator management.

However I believe we do want the ability to create a server document. Maybe even a template (ie deploy time replaceable values).. but that last piece is wip as I need to writeup some of my k8s thoughts more (delayed by release/dependencies)

So it would be good to think of that when designing the server author - ie may be different levels for view/author/manage

Also in k8s (and other deployments) bear in mind there may be replicated servers so the view is more a logical one rather than physical (ie one server is actually deployed across platforms on multiple containers or physical machines), and indeed the relationship between platform and server is managed by the deployer or deployment mechanisms.

**Comment by davidradl** [comment]
@planetf1  Hi Nigel, this is for Glossary author

**Comment by davidradl** [comment]
I have implemented - looks like it works as above.
