### ISSUE TITLE
React-UI crashes when selecting "myMetadataServer" in the Repository Explorer list

### ISSUE THREAD

**Issue by Cheapskate4711** [odpi/egeria-react-ui#301]
Dear team,

I am running the platform natively on RHEL. Whenever I try to select "myMetadataServer" in the Repositoy Explorer list the UI crashes (see attached images, pls.):

![image](https://user-images.githubusercontent.com/54888220/145387819-939648fc-015b-43de-9aa2-0337a8cf3971.png)
![image](https://user-images.githubusercontent.com/54888220/145387857-38fc35fe-f8f7-49a3-bf07-6596712f4c2e.png)

**Comment by Cheapskate4711** [comment]
[myCurrentMetaserverConfig_git.txt](https://github.com/odpi/egeria-react-ui/files/7686159/myCurrentMetaserverConfig_git.txt)
[myCurrentViewServerConfig_git.txt](https://github.com/odpi/egeria-react-ui/files/7686161/myCurrentViewServerConfig_git.txt)

**Comment by davidradl** [comment]
Hi Ian, I copied in your 2 configuration files as you supplied them, I started the metadata respository server and then the view server. It all worked for me . I used a .env file in the cra_server folder with line `"EGERIA_PRESENTATIONSERVER_SERVER_myOrg={"remoteServerName":"viewserver","remoteURL":"https://localhost:9443"}".` I logged in using `https://localhost:8091/myOrg/login `

**Comment by Cheapskate4711** [comment]
... unfortunately this did not work for me ... using the same supplied configs and stuff... 
![image](https://user-images.githubusercontent.com/54888220/146217074-842d1d35-61ec-4bdb-b901-75377d7049c5.png)

**Comment by planetf1** [comment]
I had a look at your configs earlier and couldn't see an issue either - plus @davidradl was able to run.. so I'm wondering if there could be a subtle difference in the code execution ... ?

I'm not a javascript developer, but in that error above serverInstance presumably was set on line 93, but maybe that's because of a problem of the indexing into availableServers? Yet that should come from the view service config??

* Are you running similar versions of egeria & egeria-react-ui (in case of any discrepancies between the egeria rest services & the app)? for example egeria-react-ui 3.4.0 should work well with egeria 3.4 ?
* Are you using the container-build version of the react UI? If not could you try to eliminate build issues (but this does require appropriate connectivity)
* If building locally, can you try to run similarly to the container 
 - build with node 14 (npm install / npm run build first in cra-client, then cra-server:q
 - run with 'npm run prod'

**Comment by davidradl** [comment]
@Cheapskate4711 can we close this as the issue was a configuration error on the server.I was not able to recreate this. If there is a way to recreate this for me then I could look at handling the error more elegantly.

**Comment by davidradl** [comment]
@Cheapskate4711  closing - please re open if we need to.

**Comment by Cheapskate4711** [comment]
... perfect - we solved it "last year" :-)

 

Cheers,

 

Ian

 
 

Gesendet: Donnerstag, 13. Januar 2022 um 16:45 Uhr
Von: "David Radley" ***@***.***>
An: "odpi/egeria-react-ui" ***@***.***>
Cc: "iperry" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [odpi/egeria-react-ui] React-UI crashes when selecting "myMetadataServer" in the Repository Explorer list (Issue #301)


 

@Cheapskate4711 closing - please re open if we need to.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
