### ISSUE TITLE
glossary author create relationship fails 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-react-ui#326]

**Comment by planetf1** [comment]
Can confirm I saw the same

Testing Egeria 3.5 chart
 - Egeria 3.5
 - React UI 3.4
 
 Logged in as garygeeke
 
 Created a glossary 'a'
 Created a category 'b'
 Created two terms in above 'c', 'd'
 
 All good to this point
 
 I then tried to create a 'isA' relationship 'r' between c and d using the visual explorer
 
 In the UI I got to the final screen, clicked create, and the page refreshed but no error/info was shown
 In the log of the view server I see a Bad Request:
 Full log at https://gist.github.com/e9bd7053cdcb056c85b24b53dbfcfa4e

**Comment by odttlnt** [comment]
HI Dave, Can you please assign this issue to me?

**Comment by odttlnt** [comment]
Hi All, 
So i kind of got it working. Haven't tested it through the UI, but used the swagger tool to test it. The fix is twofold
1. In the UI we need to add the property "nodeTypeName": "Term", for each end of the relationship JSON. This will have to be done on the UI.
2. The other change is in the Egeria core. The code in IsARelationshipMapper, function mapRelationshipToInstanceProperties which maps the instance properties from the relationship, needs to be updated to include the symbolic name for the TermRelationshipStatus Enum in the mapping.

I will get a PR out soon, just wanted you all to see what I found and let me know if I am on the right track before i do all the code changes

**Comment by planetf1** [comment]
Fixed
