### ISSUE TITLE
Change the browser to presentation server ssl to not use the self signed cert. 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-react-ui#74]
node.js side this will involve
- removing the self signed certificate and key files
- amend the axios create
- change the index.js when creating the server to not you the self signed certificates

**Comment by planetf1** [comment]
We'll need to do this with base egeria also.

I would expect the certs to be created by the deployer for production use
For demo purposes we would include the secrets within something like a helm chart (or instructions thereof)
So for certain all of the above should be configurable
The remaining case is 'development use' - and how we ensure that is easy, 

I think we need to default to secure by default -- so for example we could have an easy option to allow use of supplied certs, but I feel uncomfortable making it a default. I realise this impacts on usability, we need to minimise that IMO.

Re: axios unauthorized - I think this is more about ignoring whether the cert is valid 

So the thing with 'proper' certificates is that you're getting trust through third parties -- perhaps I might trust GeoTrust or Equifax to allocate certs to businesses, and then the part of my local org has allocated the IT team some certs... so I know I can trust them.

When we refer to 'self-signed' certs, we're usually saying we made up our own root certification authority, or created a cert without a CA (certification authority) -- so why should anyone trust that? So by default the code doesn't. But there's often a way of skipping that test. We can do it here in react, we can do it in our spring chassis in java (and the STRICT_SSL env var does that... because we coded it as such...)

So there may be conflation of two issues here
 a) Not using any certs by default
 b) Whether to validate the certificate (and if using 2 way SSL this occurs on both sides)
 
 For example we could eliminate b) by just ensuring the CA is available to all the places where we do the checks -- indeed this is what the docs I pointed to earlier (the TLS guide for egeria) does. There is no need to skip any kind of cert checking, since we know we can trust the egeria cert.  Now the point this breaks down is the Chrome UI - but that's only because the *browser* won't typically have the CA. But if you deployed that to the browser it would be fine.
 
 Similarly you could implement a) but if a user created their own without sorting the CA, it would not work as they couldn't script the checks.
 
 Now this skipping is a little dodgy, though most code reluctantly supports it. No way it should be the default, but I think it's worth allowing for.

**Comment by davidradl** [comment]
I am thinking that we would use a cert and passphrase from the ca for the coco scenario.

**Comment by planetf1** [comment]
> I am thinking that we would use a cert and passphrase from the ca for the coco scenario.

Sorry I'm not quite sure what you mean - can you be more specific?

My plan is that we have an EgeriaCA we create (for demos, out of the box -- will be replaced by a reference to internet defaults or org specific CA in the real world).
That CA is used to create all of our other certificates.
In general we protect the keys, and .p12 files with a passphrase. Each is technically unique, though most likely we'll default to the same value

**Comment by davidradl** [comment]
this is related to #73 and #76.
